server:
  port: ${SERVER_PORT}
  compression:
    enabled: true
    min-response-size: 1

logging:
  charset:
    file: UTF-8
  level:
    ru.sberbank.femida.ms.user.controller: info # debug - логирование реквеста, info - без
    ru.morningcake.component.PostFifoCache: debug # debug - логирование кэша постов, info - без
    org.springframework.transaction: debug
#    org.hibernate.SQL: info

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: ms-user
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: validate #update
    properties:
      hibernate:
        id.new_generator_mappings: true
        globally_quoted_identifiers: true
        jdbc.lob.non_contextual_creation: true
        default_schema: ${DB_SCHEMA}
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-wait: 10000
      max-active: 10
      test-on-borrow: true
      max-idle: 10
    hikari:
      pool-name: OtusMsUserPool
  liquibase:
    default-schema: ${DB_SCHEMA}
    enabled: true

app:
  cache:
    posts.size: ${POSTS_CACHE_SIZE:1000}
  emulation.posts:
    enabled: ${POSTS_EMULATION_ENABLED:true}
    delay: ${POSTS_EMULATION_DELAY:1} # interval, minutes
    initDelay: ${POSTS_EMULATION_INIT_DELAY:2} # after app start, minutes
    filePath: ${POSTS_EMULATION_FILE_PATH:src/main/resources/db/changelog/1.2.0/posts/posts.txt} # posts text file. Every post in new string
    qnt: ${POSTS_EMULATION_QNT:1} # user posts add in single iteration
    annId: ${ANN_ID:ac172001-9327-19ff-8193-2770af5f0000} # ID of our user Ann