server:
  port: 11100
  compression:
    enabled: true
    min-response-size: 1

logging:
  charset:
    file: UTF-8
  level:
    ru.sberbank.femida.ms.user.controller: info # debug - логирование реквеста, info - без
#    org.hibernate.SQL: info

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: ms-user
  jackson:
    default-property-inclusion: non_null
#  jpa:
#    show-sql: true
#    hibernate:
#      use-new-id-generator-mappings: true
#      ddl-auto: none #validate
#    properties:
#      hibernate:
#        id.new_generator_mappings: true
#        globally_quoted_identifiers: true
#        jdbc.lob.non_contextual_creation: true
#        default_schema: otus_user
#        format_sql: true
#        use_sql_comments: true
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
#    open-in-view: true
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASS}
#    driver-class-name: org.postgresql.Driver
#    tomcat:
#      max-wait: 10000
#      max-active: 10
#      test-on-borrow: true
#      max-idle: 10
#    hikari:
#      pool-name: OtusMsUserPool
#  liquibase:
#    default-schema: otus_user
#    enabled: false